### PR TITLE
FOGL-2497 Add protection in destructor to prevent crashes on shutdown

### PR DESCRIPTION
**Pull request by MarkRiddoch**

### CODE REVIEW

**Review by pintomax — APPROVED** [review]

**Comment by praveen-garg** [comment]
does that happen with foglamp restart only? or plugin_shutdown is not being called with modbus service disable?

**Comment by MarkRiddoch** [comment]
> does that happen with foglamp restart only? or plugin_shutdown is not being called with modbus service disable?

From the plugin perspective they are the same event, it can not really tell the difference at the time the destructor is called.

**Review by AmandeepArora — APPROVED** [review]
Looks good.

**Comment by praveen-garg** [comment]
> > does that happen with foglamp restart only? or plugin_shutdown is not being called with modbus service disable?
> 
> From the plugin perspective they are the same event, it can not really tell the difference at the time the destructor is called.

Yeah exactly! The crash appeared to be happening on FogLAMP restart only and not the disable/ enable -- just some timing issue? And it was supposed to happen with any of these two events (ultimately the plugin shutdown call for modbus schedule / service) ?

**Comment by MarkRiddoch** [comment]
> > > does that happen with foglamp restart only? or plugin_shutdown is not being called with modbus service disable?
> > 
> > 
> > From the plugin perspective they are the same event, it can not really tell the difference at the time the destructor is called.
> 
> Yeah exactly! The crash appeared to be happening on FogLAMP restart only and not the disable/ enable -- just some timing issue? And it was supposed to happen with any of these two events (ultimately the plugin shutdown call for modbus schedule / service) ?

Yes, there is a relatively small window in which a problem might occur, I would to expect to see it every time.

**Review by praveen-garg — APPROVED** [review]

**Comment by praveen-garg** [comment]
I was not able to reproduce with FogLAMP restart withOUT this fix, as well; and issues was never seen with disable/ enable.

**Comment by AmandeepArora** [comment]
@praveen-garg : The failure window would be very small at slow polling rate, so you might see the interleave between poll and shutdown, say once in 10-100 tries. Chances would increase if polling rate is increased, if that is possible. FogLAMP restart and disable/enable doesn't make a difference.

**Pull request merged**
